#!/usr/bin/env bash

echo ""
echo "🧭 zomi-syl CLI Commands"
echo "----------------------------------"
echo ""
echo "Core commands:"
echo "  • python -m zomi_syl syllabify \"themthum\""
echo "  • python -m zomi_syl syllabify --backend rule \"kiginna\""
echo "  • python -m zomi_syl syllabify --backend crf \"kiginna\""
echo ""
echo "Other useful commands:"
echo "  • python -m zomi_syl analyze \"themthum\""
echo "  • python -m zomi_syl batch --input file.txt --output out.tsv"
echo "  • python -m zomi_syl models list"
echo "  • python -m zomi_syl profiles list"
echo "  • python -m zomi_syl profiles validate tedim"
echo "  • python -m zomi_syl profiles validate zolai_standard"
echo "  • python -m zomi_syl profiles validate myanmar_zomi"
echo "  • python -m zomi_syl benchmark --backend crf"
echo ""
echo "Flags:"
echo "  --backend <rule|crf|transformer>"
echo "  --profile <tedim|zolai_standard|myanmar_zomi>"
echo ""
echo "----------------------------------"
echo "Tip: Use 'python -m zomi_syl <command> --help' for detailed usage."
echo ""
