name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you running this manually?"
        required: false
        default: "manual run"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clean dist
        run: find . -maxdepth 3 -type d -name "dist" -exec rm -rf {} +

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Inspect wheel
        run: |
          pip install wheel
          unzip -l dist/*.whl
      
      - name: Show wheel metadata
        run: |
          WHEEL=$(ls dist/*.whl | head -1)
          echo "Wheel: $WHEEL"

          unzip -l "$WHEEL"

          METADATA_PATH=$(zipinfo -1 "$WHEEL" | grep '\.dist-info/METADATA$')

          echo "METADATA file: $METADATA_PATH"
          unzip -p "$WHEEL" "$METADATA_PATH" | head -50
      
      - name: Check distribution
        run: |
          python -m pip install --upgrade twine
          twine check dist/*
  
      - name: Debug dist directories
        run: |
          echo "INNER DIST:"
          ls -R dist || true
          echo "OUTER DIST:"
          ls -R ../dist || true
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.0
        with:
          packages_dir: dist
